// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXZcpLr1zIgIeOummbmvbQHuEEEikbZOI',
    appId: '1:554921844880:web:628fe1f27bab6ce0b47815',
    messagingSenderId: '554921844880',
    projectId: 'chat-45393',
    authDomain: 'chat-45393.firebaseapp.com',
    storageBucket: 'chat-45393.appspot.com',
    measurementId: 'G-K8KM7E9K6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiGdQJxrJsck5qRuPmbcI18z75ZTeGumY',
    appId: '1:554921844880:android:3c367d7680e07d73b47815',
    messagingSenderId: '554921844880',
    projectId: 'chat-45393',
    storageBucket: 'chat-45393.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_44gNGc068WAbTi3bKg_bRJnMWt2qWUY',
    appId: '1:554921844880:ios:1d3e76e49da677d1b47815',
    messagingSenderId: '554921844880',
    projectId: 'chat-45393',
    storageBucket: 'chat-45393.appspot.com',
    iosClientId: '554921844880-9b8p9j2c8kfero9u56n9aednqk8ab7j8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
